alter table DHS_MMIS_DW_TGT.DW_DSS_MED_CLM ADD ENC_CLAIM_STATUS_CD VARCHAR2(2 BYTE); 
alter table DHS_MMIS_DW_TGT.DW_DSS_MED_CLM ADD ENC_LI_STS_CD VARCHAR2(2 BYTE), 
alter table DHS_MMIS_DW_TGT.DW_DSS_MED_CLM ADD CLM_OTHER_CLM_ID VARCHAR2(30 BYTE);

alter table DHS_MMIS_DW_TGT.DW_DSS_DRUG_CLM ADD ENC_CLAIM_STATUS_CD VARCHAR2(2 BYTE); 
alter table DHS_MMIS_DW_TGT.DW_DSS_DRUG_CLM ADD ENC_LI_STS_CD VARCHAR2(2 BYTE), 
alter table DHS_MMIS_DW_TGT.DW_DSS_DRUG_CLM ADD CLM_OTHER_CLM_ID VARCHAR2(30 BYTE);